/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import javax.swing.JOptionPane;

/**
 *
 * @author AY
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        mniPresentar = new javax.swing.JMenu();
        mnRegistrar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniPresentarMoto = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        mniFiltrar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniEditar = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mniEliminar = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnSalir = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        mniAutor = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu de Moto \"Yamuva\"");
        setSize(new java.awt.Dimension(0, 0));

        mniPresentar.setText("Moto");

        mnRegistrar.setText("Registrar");
        mnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRegistrarActionPerformed(evt);
            }
        });
        mniPresentar.add(mnRegistrar);
        mniPresentar.add(jSeparator1);

        mniPresentarMoto.setText("Presentar");
        mniPresentarMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPresentarMotoActionPerformed(evt);
            }
        });
        mniPresentar.add(mniPresentarMoto);
        mniPresentar.add(jSeparator6);

        jMenu3.setText("Filtrar");

        mniFiltrar.setText("xSistema y Tipo");
        mniFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFiltrarActionPerformed(evt);
            }
        });
        jMenu3.add(mniFiltrar);

        mniPresentar.add(jMenu3);
        mniPresentar.add(jSeparator2);

        mniEditar.setText("Editar");
        mniEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEditarActionPerformed(evt);
            }
        });
        mniPresentar.add(mniEditar);
        mniPresentar.add(jSeparator4);

        mniEliminar.setText("Eliminar");
        mniEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEliminarActionPerformed(evt);
            }
        });
        mniPresentar.add(mniEliminar);
        mniPresentar.add(jSeparator3);

        mnSalir.setText("Salir");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        mniPresentar.add(mnSalir);
        mniPresentar.add(jSeparator5);

        jMenuBar1.add(mniPresentar);

        jMenu2.setText("Ayuda");

        mniAutor.setText("Informacion");
        mniAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAutorActionPerformed(evt);
            }
        });
        jMenu2.add(mniAutor);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnSalirActionPerformed

    private void mnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRegistrarActionPerformed
        FrmRegistrarMoto frm = new FrmRegistrarMoto(this, true);
        frm.setVisible(true);
        
    }//GEN-LAST:event_mnRegistrarActionPerformed

    private void mniPresentarMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPresentarMotoActionPerformed
        FrmPresentarMoto frm = new FrmPresentarMoto(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_mniPresentarMotoActionPerformed

    private void mniFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFiltrarActionPerformed
        FrmFiltrar frm = new FrmFiltrar(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_mniFiltrarActionPerformed

    private void mniAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAutorActionPerformed
        FrmAyuda frm = new FrmAyuda(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_mniAutorActionPerformed

    private void mniEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEditarActionPerformed
        FrmEditar frm = new FrmEditar(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_mniEditarActionPerformed

    private void mniEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEliminarActionPerformed
        FrmEliminar frm = new FrmEliminar(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_mniEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    javax.swing.JMenuItem mnRegistrar;
    private javax.swing.JMenuItem mnSalir;
    private javax.swing.JMenuItem mniAutor;
    javax.swing.JMenuItem mniEditar;
    javax.swing.JMenuItem mniEliminar;
    javax.swing.JMenuItem mniFiltrar;
    private javax.swing.JMenu mniPresentar;
    javax.swing.JMenuItem mniPresentarMoto;
    // End of variables declaration//GEN-END:variables
}
