/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import Control.AdmMoto;

/**
 *
 * @author AY
 */
public class FrmPresentarMoto extends javax.swing.JDialog {
    
    private AdmMoto adm= AdmMoto.getAdm();
    

    /**
     * Creates new form FrmPresentarMoto
     */
    
    
    public FrmPresentarMoto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        adm.llenarTabla(tabPresentar);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabPresentar = new javax.swing.JTable();
        btnPresentar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Presentar Moto");

        tabPresentar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Sistema", "Placa", "Marca", "Modelo", "Color", "Tipo", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabPresentar.setToolTipText("");
        tabPresentar.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabPresentar);
        if (tabPresentar.getColumnModel().getColumnCount() > 0) {
            tabPresentar.getColumnModel().getColumn(0).setResizable(false);
            tabPresentar.getColumnModel().getColumn(1).setResizable(false);
            tabPresentar.getColumnModel().getColumn(2).setResizable(false);
            tabPresentar.getColumnModel().getColumn(3).setResizable(false);
            tabPresentar.getColumnModel().getColumn(4).setResizable(false);
            tabPresentar.getColumnModel().getColumn(5).setResizable(false);
            tabPresentar.getColumnModel().getColumn(6).setResizable(false);
            tabPresentar.getColumnModel().getColumn(7).setResizable(false);
        }

        btnPresentar.setText("Aceptar");
        btnPresentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresentarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPresentar)
                .addGap(309, 309, 309))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPresentar)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPresentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresentarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnPresentarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnPresentar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabPresentar;
    // End of variables declaration//GEN-END:variables
}
